version: "3"
services:
  app:
    build: "./app"
    container_name: "twitter_app"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./:/project"
    command: "bash -c 'cd /project/app && npm start'"
    tty: true
  api:
    build: "./api"
    container_name: "twitter_api"
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "./:/project"
    command: "rails server -b '0.0.0.0' -p 80"
    tty: true
